---
title: "Analysis"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
df <- read.csv("/Users/nick/Desktop/CSP571_Movie_Profits_Project/final_dataset.csv")
df_model <- df[c("actorRank", "runtime", "ProductionBudget", "quarter", "drama", "thriller", "nonfiction", "action", "amusement", "Success_2_to_1")]
df_continuous <- df[c("runtime", "ProductionBudget", "DomesticGross")]
```

## Including Plots

You can also embed plots, for example:

```{r}
library('fastDummies')
maxs <- apply(df_model, 2, max)
mins <- apply(df_model, 2, min)

df_scaled_cont <- scale(df_continuous) 
df_model[c("runtime", "ProductionBudget")] <- df_scaled_cont
df_model <- fastDummies::dummy_cols(df_model, select_columns = 'quarter')
df_model$quarter <- NULL
```


```{r}

set.seed(1000)
library('caret')
library('neuralnet')
inTrain <- createDataPartition(y = df_model[,'Success_2_to_1'], list = FALSE, p = 0.8)
train <- df_model[inTrain,]
test <- df_model[-inTrain,]


#Neural Network
library(neuralnet)
max_p <- 0
best_parameters <- c()
nn <- neuralnet(Success_2_to_1 ~ ., data=train, hidden=c(5,5), stepmax = 500000, rep=5, linear.output=FALSE, threshold=0.05)
nn$result.matrix
plot(nn)

temp_test <- test
temp_test$Success_2_to_1 <- NULL

nn.results <- compute(nn, temp_test)
results <- data.frame(actual=test$Success_2_to_1, prediction=nn.results$net.result)

roundedresults<-sapply(results,round,digits=0)
roundedresultsdf=data.frame(roundedresults)
attach(roundedresultsdf)
table(actual,prediction)


```

```{r}
temp_test <- test
temp_test$Success_2_to_1 <- NULL

nn.results <- compute(nn, temp_test)
results <- data.frame(actual=test$Success_2_to_1, prediction=nn.results$net.result)
```

```{r}
roundedresults<-sapply(results,round,digits=0)
roundedresultsdf=data.frame(roundedresults)
attach(roundedresultsdf)
table(actual,prediction)

```






